/**
 * A PercussionSet corresponding to the instruments of GM2 Standard Percussion Set.
 *
 * (C) 2021 Malcolm Tyrrell
 *
 * Licensed under the GPLv3.0. See LICENSE file.
 **/
#include <Plugins/Smf/Plugin/Percussion/gm2OrchestraPercussionSet.hpp>

smf::GM2OrchestraPercussionSet::GM2OrchestraPercussionSet(
    const bw_music::BuiltInPercussionInstruments& builtInInstruments)
    : PercussionSetWithPitchMap(InstrumentBlock{{bw_music::BuiltInPercussionInstruments::Value::ClHH2,
                                                 bw_music::BuiltInPercussionInstruments::Value::PdHHat,
                                                 bw_music::BuiltInPercussionInstruments::Value::OpHH2,
                                                 bw_music::BuiltInPercussionInstruments::Value::Ride1,
                                                 bw_music::BuiltInPercussionInstruments::Value::Stcks,
                                                 bw_music::BuiltInPercussionInstruments::Value::SqClck,
                                                 bw_music::BuiltInPercussionInstruments::Value::MtrClk,
                                                 bw_music::BuiltInPercussionInstruments::Value::MtrBll,
                                                 bw_music::BuiltInPercussionInstruments::Value::CnBD2,
                                                 bw_music::BuiltInPercussionInstruments::Value::CnBD1,
                                                 bw_music::BuiltInPercussionInstruments::Value::SStick,
                                                 bw_music::BuiltInPercussionInstruments::Value::CnSD,
                                                 bw_music::BuiltInPercussionInstruments::Value::Cstnts,
                                                 bw_music::BuiltInPercussionInstruments::Value::CnSD,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpF,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpFs,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpG,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpGs,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpA,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpAs,
                                                 bw_music::BuiltInPercussionInstruments::Value::TimpB,
                                                 bw_music::BuiltInPercussionInstruments::Value::Timpc,
                                                 bw_music::BuiltInPercussionInstruments::Value::Timpcs,
                                                 bw_music::BuiltInPercussionInstruments::Value::Timpd,
                                                 bw_music::BuiltInPercussionInstruments::Value::Timpds,
                                                 bw_music::BuiltInPercussionInstruments::Value::Timpe,
                                                 bw_music::BuiltInPercussionInstruments::Value::Timpf,
                                                 bw_music::BuiltInPercussionInstruments::Value::Tamb,
                                                 bw_music::BuiltInPercussionInstruments::Value::SplCym,
                                                 bw_music::BuiltInPercussionInstruments::Value::Cowbll,
                                                 bw_music::BuiltInPercussionInstruments::Value::Crash2,
                                                 bw_music::BuiltInPercussionInstruments::Value::CnCym2,
                                                 bw_music::BuiltInPercussionInstruments::Value::Ride2,
                                                 bw_music::BuiltInPercussionInstruments::Value::CnCym1,
                                                 bw_music::BuiltInPercussionInstruments::Value::LBongo,
                                                 bw_music::BuiltInPercussionInstruments::Value::MHCnga,
                                                 bw_music::BuiltInPercussionInstruments::Value::OHCnga,
                                                 bw_music::BuiltInPercussionInstruments::Value::LConga,
                                                 bw_music::BuiltInPercussionInstruments::Value::HTimbl,
                                                 bw_music::BuiltInPercussionInstruments::Value::LTimbl,
                                                 bw_music::BuiltInPercussionInstruments::Value::HAgogo,
                                                 bw_music::BuiltInPercussionInstruments::Value::LAgogo,
                                                 bw_music::BuiltInPercussionInstruments::Value::Cabasa,
                                                 bw_music::BuiltInPercussionInstruments::Value::Maracs,
                                                 bw_music::BuiltInPercussionInstruments::Value::SWhisl,
                                                 bw_music::BuiltInPercussionInstruments::Value::LWhisl,
                                                 bw_music::BuiltInPercussionInstruments::Value::SGuiro,
                                                 bw_music::BuiltInPercussionInstruments::Value::LGuiro,
                                                 bw_music::BuiltInPercussionInstruments::Value::Claves,
                                                 bw_music::BuiltInPercussionInstruments::Value::HWoodB,
                                                 bw_music::BuiltInPercussionInstruments::Value::LWoodB,
                                                 bw_music::BuiltInPercussionInstruments::Value::MCuica,
                                                 bw_music::BuiltInPercussionInstruments::Value::OCuica,
                                                 bw_music::BuiltInPercussionInstruments::Value::MTrian,
                                                 bw_music::BuiltInPercussionInstruments::Value::OTrian,
                                                 bw_music::BuiltInPercussionInstruments::Value::Shaker,
                                                 bw_music::BuiltInPercussionInstruments::Value::JngBll,
                                                 bw_music::BuiltInPercussionInstruments::Value::BlTree,
                                                 bw_music::BuiltInPercussionInstruments::Value::Cstnts,
                                                 bw_music::BuiltInPercussionInstruments::Value::MSurdo,
                                                 bw_music::BuiltInPercussionInstruments::Value::OSurdo,
                                                 bw_music::BuiltInPercussionInstruments::Value::Aplaus},
                                                27,
                                                &builtInInstruments},
                                27) {}
